### ISSUE TITLE
It is not possible to define different definition domains for multiple formulas

### ISSUE THREAD

**Issue by Li-Juan-Siwei** [MarcosNicolau/obsidian-mathematica-plot#1]

**Comment by Li-Juan-Siwei** [comment]
y = x, -5<x<5
y = x^2, 5<x<10
How to draw it?

**Comment by MarcosNicolau** [comment]
Hi @Elliootalderson,

Oh, I see what is going on there...  y = x^2 is not on the view of y = x for any value of x. You need to tell Wolfram to adjust the view by setting PlotRange to Automatic or Full under the general directive. That'll be `others: PlotRange -> Automatic`

Here is the full code,

```yml
raster:
  dim: 2D
  background: None
  size:
    height: Automatic
    width: "250"
general:
  axes: "True"
  axesLabel: "{x, y}"
  frame: "False"
  boxed: "True"
  others: PlotRange -> Automatic
graphs:
  - id: graph_0
    options: {}
    type: plot
    plot:
      expression: x
      plotRange:
        x:
          min: "-5"
          max: "5"
  - id: graph_1
    options: {}
    type: plot
    plot:
      expression: x^2
      plotRange:
        x:
          min: "5"
          max: "10"
 ```

I thought that was the default behavior in wolfram... I'll make sure to add that option as default in the next release. 

Btw, you can't add the `others` options from the command modal, I'll make sure to add that as well! :grin: 

Thx for the issue and the contribution! :+1:
