### ISSUE TITLE
Plot range not automatically adjusting based on plots domains

### ISSUE THREAD

**Issue by MarcosNicolau** [MarcosNicolau/obsidian-mathematica-plot#2]
When drawing functions with different domains, the plot does not automatically adjust its view to contain them. 

The current workaround until the fix is to add: `others: PlotRange -> Automatic` under the `general` directive in the generated yml (can't add this from the command modal).

The yml should look like:

```yml
raster:
general:
    ...
    others: PlotRange -> Automatic
graphs:
```
